
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zeynep
 */
public class MusteriEkrani extends javax.swing.JFrame {

    DefaultTableModel model;
    private PreparedStatement preparedstatement=null;
    public MusteriEkrani() {
        initComponents();
        model=new DefaultTableModel();
        model=(DefaultTableModel) kundeTable.getModel();
    }
    public ArrayList<Kunde> getKunde() throws SQLException{
         Baglanti a=new Baglanti();
         String sorgu="SELECT tbKunde.CustomerID,tbKunde.CustomerName,InspectionPlace.District,InspectionPlace.Province,JobOrder.JobOrderNo,Offer.OfferNo  FROM tbKunde INNER JOIN InspectionPlace ON tbKunde.InspectionPlaceID=InspectionPlace.InspectionPlaceID INNER JOIN JobOrder ON tbKunde.CustomerID=JobOrder.CustomerID INNER JOIN Offer ON tbKunde.CustomerID=Offer.CustomerID ORDER BY tbKunde.CustomerID";
         ArrayList<Kunde>k=null;
    
     
     try {
         a.statement=a.con.createStatement();
         ResultSet rs=a.statement.executeQuery(sorgu);
         k=new ArrayList<Kunde>();
         
         while(rs.next()){
             
            int cid=rs.getInt("CustomerID");
            String name=rs.getString("CustomerName");
            String district=rs.getString("District");
            String province=rs.getString("Province");
            int joborder=rs.getInt("JobOrderNo");
            int offer=rs.getInt("OfferNo");
            k.add(new Kunde(name,district,province,offer,joborder,cid));
            
             
             
            
             
             
         }
         
         
         
     } catch (SQLException ex) {
         Logger.getLogger(Baglanti.class.getName()).log(Level.SEVERE, null, ex);
     }
        return k;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kundeTable = new javax.swing.JTable();
        listKunde = new javax.swing.JButton();
        backKunde = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kundeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Customer Name", "District", "Province", "Job Order No", "Offer No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kundeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kundeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(kundeTable);

        listKunde.setText("List");
        listKunde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listKundeActionPerformed(evt);
            }
        });

        backKunde.setText("Back");
        backKunde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backKundeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listKunde))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backKunde)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listKunde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(backKunde)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kundeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kundeTableMouseClicked
        // TODO add your handling code here:
        

    }//GEN-LAST:event_kundeTableMouseClicked

    private void listKundeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listKundeActionPerformed
      try {
           ArrayList<Kunde> k=getKunde();
           for(Kunde kunde:k){
               Object[] row={kunde.getCustomerID(),kunde.getName(),kunde.getDistrict(),kunde.getProvince(),kunde.getOfferNo(),kunde.getJobOrderNo()};
               model.addRow(row);
           }
       } catch (SQLException ex) {
           Logger.getLogger(PersonelInformation.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_listKundeActionPerformed

    private void backKundeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backKundeActionPerformed
    Anasayfa a=new Anasayfa();
    a.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_backKundeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backKunde;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable kundeTable;
    private javax.swing.JButton listKunde;
    // End of variables declaration//GEN-END:variables
}
